# Generated by Django 3.2.12 on 2022-05-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre_likes',
            field=models.JSONField(default='{}'),
        ),
    ]
