# Generated by Django 3.2.12 on 2022-05-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_genre_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre_likes',
        ),
    ]
