# Generated by Django 3.2.12 on 2022-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220518_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre_likes',
            field=models.JSONField(default='{}'),
        ),
    ]
