# Generated by Django 3.2.12 on 2022-05-18 15:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_genre_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_img'),
        ),
    ]
