# Generated by Django 3.2.12 on 2022-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre_likes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.TextField(blank=True, default='https://assets.repress.co.kr/photos/2009ea104d2c842fed5461308d9f92d7/original.jpg'),
        ),
    ]
