# Generated by Django 3.2.12 on 2022-05-17 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movie_genres', to='movies.Genre'),
        ),
        migrations.CreateModel(
            name='MovieFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kept_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_movies', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_follows', to='movies.movie')),
            ],
        ),
    ]
