# Generated by Django 3.2.12 on 2022-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220519_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
    ]
